/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelOPliku.java
 *
 * Created on 2011-11-20, 23:19:50
 */
package elpenor.gui;

import java.text.DecimalFormat;

/**
 *
 * @author darian
 */
public class PanelOPliku extends javax.swing.JPanel {

    /** Creates new form PanelOPliku */
    public PanelOPliku() {
        initComponents();
    }
    
    public void wyczyscDane() {
        this.setVisible(false);
        this.tekstBrakZaładowanegoPliku.setVisible(true);
        
        this.nazwa.setText("");
        this.rozmiarPrzed.setText("");
        this.rozmiarPo.setText("");
        this.ustawStopieńKompresji(0);
        
        this.setVisible(true);
    }
    
    public void wstawDane(String nazwa, int rozmiarPrzed, int rozmiarPo) {
        
        this.setVisible(false);
        
        this.tekstBrakZaładowanegoPliku.setVisible(false);
        
        this.nazwa.setText(nazwa);
        this.rozmiarPrzed.setText(Integer.toString(rozmiarPrzed));
        this.rozmiarPo.setText(Integer.toString(rozmiarPo));
        this.ustawStopieńKompresji((double)rozmiarPo/rozmiarPrzed);
        
        this.setVisible(true);
    }
    
    private void ustawStopieńKompresji(double sk) {
        
        if (sk >= 0) {
            sk *= 100;
            DecimalFormat df = new DecimalFormat("#.###");
            
            stopieńKompresji.setText(df.format(sk) + " %");
        } else {
            stopieńKompresji.setText("");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tekstInfoOPliku = new javax.swing.JLabel();
        tekstBrakZaładowanegoPliku = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        stopieńKompresji = new javax.swing.JLabel();
        nazwa = new javax.swing.JLabel();
        rozmiarPrzed = new javax.swing.JLabel();
        rozmiarPo = new javax.swing.JLabel();

        tekstInfoOPliku.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        tekstInfoOPliku.setText("Informacje o pliku");

        tekstBrakZaładowanegoPliku.setForeground(new java.awt.Color(225, 1, 1));
        tekstBrakZaładowanegoPliku.setText("Brak załadowanego pliku");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nazwa:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Rozmiar przed:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Rozmiar po:");

        jLabel6.setText("Stopień kompresji:");

        stopieńKompresji.setFont(new java.awt.Font("DejaVu Sans", 1, 24));
        stopieńKompresji.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stopieńKompresji.setText("0 %");

        nazwa.setText(" ");

        rozmiarPrzed.setText(" ");

        rozmiarPo.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tekstInfoOPliku, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tekstBrakZaładowanegoPliku)
                    .addComponent(jLabel6)
                    .addComponent(stopieńKompresji, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nazwa, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(rozmiarPrzed, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(rozmiarPo, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tekstInfoOPliku, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tekstBrakZaładowanegoPliku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazwa)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rozmiarPrzed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rozmiarPo))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stopieńKompresji, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel nazwa;
    private javax.swing.JLabel rozmiarPo;
    private javax.swing.JLabel rozmiarPrzed;
    private javax.swing.JLabel stopieńKompresji;
    private javax.swing.JLabel tekstBrakZaładowanegoPliku;
    private javax.swing.JLabel tekstInfoOPliku;
    // End of variables declaration//GEN-END:variables
}
